blog/urls.py
from blog import views
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("sign-up/", views.sign_up, name="sign_up"),
    path("log-out/", views.log_out, name="log_out"),
    path("", views.post_list, name="post_list"),
    path("post/new", views.post_create, name="post_create"),
    path("post/<int:pk>/", views.post_detail, name="post_detail"),
    path("post/<int:pk>/edit", views.post_edit, name="post_edit"),
    path(
        "post/category/<int:category_id>",
        views.post_list_by_category,
        name="post_category",
    ),
    path("post/comment/<int:comment_id>/edit", views.comment_edit, name="comment_edit"),
    path(
        "post/comment/<int:comment_id>/delete",
        views.comment_delete,
        name="comment_delete",
    ),
    path("post/comment/<int:pk>/create", views.post_comment, name="post_comment"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("", include("django.contrib.auth.urls")),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

# # Define permission
# content_type = ContentType.objects.get(app_label="blog", model="comment")

# if not Permission.objects.filter(
#     codename="can_edit_comment", content_type=content_type
# ).exists():
#     Permission.objects.create(
#         codename="can_delete_comment",
#         name="Can delete the post comment",
#         content_type=content_type,
#     )

# if not Permission.objects.filter(
#     codename="can_delete_comment", content_type=content_type
# ).exists():
#     Permission.objects.create(
#         codename="can_delete_comment",
#         name="Can delete the post comment",
#         content_type=content_type,
#     )

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ManyToManyField(Category)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey("auth.user", on_delete=models.CASCADE)
    text = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Comment, Category
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import re


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text", "category"]
        widgets = {"category": forms.CheckboxSelectMultiple}

    def clean_text(self):
        KATA_KOTOR_LIST = ["anjing", "goblok", "kampret", "asw", "jancok"]
        text = self.cleaned_data["text"]

        for kata_kotor in KATA_KOTOR_LIST:
            text = text.replace(kata_kotor, "***")

        return text
        # for kata_kotor in KATA_KOTOR_LIST:
        #     if re.search(kata_kotor, string)


# def clean_text(self):
#     if self.cleaned_data["text"] in self.KATA_KOTOR:
#         for kata_kotor in self.KATA_KOTOR:
#             # print(kata_kotor)
#             if kata_kotor in self.cleaned_data["text"]:
#                 self.cleaned_data["text"] = self.cleaned_data["text"].replace(
#                     kata_kotor, "***"
#                 )

#     return self.cleaned_data["text"]

# kata_kotor = self.cleaned_data["text"].find("asw")
# print(kata_kotor)
# if kata_kotor:

# for kata in self.cleaned_data['text']:
#     print(kata)
# self.add_error("text", "error kata kotor")

# if Post.objects.filter(
#     text__in=["anjing", "goblok", "kampret", "asw", "jancok"]
# ):


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]


class PostFilterForm(forms.Form):
    title = forms.CharField(required=False)
    author = forms.CharField(required=False)
    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )
    # category = forms.ChoiceField(
    #     label="Radio Button", widget=forms.RadioSelect, queryset=Category.objects.all()
    # )
    start_date = forms.DateField(required=False, widget=forms.SelectDateWidget())
    end_date = forms.DateField(required=False, widget=forms.SelectDateWidget())

    def clean(self):
        if self.cleaned_data["start_date"] > self.cleaned_data["end_date"]:
            self.add_error("start_date", "start date must be less than end date")
            self.add_error("end_date", "start date must be less than end date")
            # raise ValidationError("start date must be less than end date")


class EditPostForm(forms.Form):
    # fields = ["title", "text", "category"]
    title = forms.CharField()
    text = forms.CharField(widget=forms.Textarea)
    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple
    )

    def clean_text(self):
        KATA_KOTOR_LIST = ["anjing", "goblok", "kampret", "asw", "jancok"]
        text = self.cleaned_data["text"]

        for kata_kotor in KATA_KOTOR_LIST:
            # just replace kata kotor with "***", no need create validation wheter kata kotor is in text or not
            text = text.replace(kata_kotor, "***")

        return text

    def save(self, post):
        post.title = self.cleaned_data["title"]
        post.text = self.cleaned_data["text"]
        post.category.set(self.cleaned_data["category"])
        post.save()

blog/views.py
from .models import Post, Category, Comment
from .forms import PostForm, CommentForm, PostFilterForm, RegisterForm, EditPostForm
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.db.models import Q, Count
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, permission_required


def sign_up(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        # check user input in RegisterForm is valid or not
        if form.is_valid():
            user = form.save()
            return redirect("/login")

    # if method is GET then run the following code
    else:
        form = RegisterForm()

    return render(request, "registration/sign_up.html", {"form": form})


def log_out(request):
    logout(request)
    return redirect("login")


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by(
        "published_date"
    )
    post_count_by_author = Post.objects.values("author__username").annotate(
        post_count=Count("id")
    )

    category_count_by_post = Category.objects.values("name").annotate(
        post_count=Count("post")
    )

    form = PostFilterForm(request.POST or None)
    start_date = end_date = None
    if request.method == "POST":
        # form = PostFilterForm(request.POST)
        if form.is_valid():
            # get data from the form
            title = form.cleaned_data["title"]
            author = form.cleaned_data["author"]
            category = request.POST.getlist("category")
            start_date = form.cleaned_data["start_date"]
            end_date = form.cleaned_data["end_date"]

            filters = Q()

            if title:
                filters &= Q(title__icontains=title)

            if author:
                filters &= Q(author__username=author)

            if category:
                filters &= Q(category__in=category)

            if start_date and end_date:
                filters &= Q(published_date__gte=start_date) or Q(
                    published_date__lte=end_date
                )

            posts = Post.objects.filter(filters)
        else:
            print(form.errors)
    # else:
    #     form = PostFilterForm()

    return render(
        request,
        "blog/post_list.html",
        {
            "form": form,
            "posts": posts,
            "post_count_by_author": post_count_by_author,
            "category_count_by_post": category_count_by_post,
        },
    )


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    form = CommentForm()

    return render(
        request,
        "blog/post_detail.html",
        {"post": post, "form": form},
    )


@login_required(login_url="/login")
def post_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect("blog:post_detail", pk=pk)

    return redirect("blog:post_detail", pk=pk)


@login_required(login_url="/login")
def post_create(request):
    KATA_KOTOR = ["anjing", "goblok", "kampret", "asw", "jancok"]

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            # body_text = request.POST["text"]
            # if KATA_KOTOR in body_text:
            #     censored_text = body_text.replace(KATA_KOTOR, "***")
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect("blog:post_detail", pk=post.pk)
    else:
        form = PostForm()

    return render(request, "blog/post_create.html", {"form": form})


@login_required(login_url="/login")
def post_edit(request, pk):
    # get post data (object based on id)
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        # put post object into form
        form = EditPostForm(request.POST)
        if form.is_valid():
            form.save(post)
            return redirect("blog:post_detail", pk=post.pk)
    else:
        print("post :", post)
        # print("post category:", post.categories)
        form = EditPostForm(
            initial={
                "title": post.title,
                "text": post.text,
                "category": post.category.all(),
            }
        )

    return render(request, "blog/post_edit.html", {"form": form})


def post_list_by_category(request, category_id):
    """Display a list of posts in a given category id

    Args:
        request (HttpRequest)   : The incoming HTTP request
        category_id (int)       : category id that got from client

    Returns:
        HttpResponse    : The HTTP response to be sent to the client
    """
    posts = Post.objects.filter(category__id=category_id)

    return render(request, "blog/post_list.html", {"posts": posts})


@login_required(login_url="/login")
@permission_required("blog.change_comment", login_url="/login", raise_exception=True)
def comment_edit(request, comment_id):
    """ """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            if request.user == comment.author or request.user.is_superuser:
                comment.save()
                return redirect("blog:post_detail", pk=comment.post.id)
            else:
                return redirect("blog:post_list")
    else:
        form = CommentForm(initial={"text": comment.text})

    return render(request, "blog/comment_edit.html", {"form": form, "comment": comment})


@login_required(login_url="/login")
@permission_required("blog.delete_comment", login_url="/login", raise_exception=True)
def comment_delete(request, comment_id):
    """TODO"""
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == "POST":
        comment.delete()
        return redirect("blog:post_detail", pk=comment.post.id)

    return HttpResponse(status=405)


# Create your views here.
# def post_list(request):
#     posts = Post.objects.filter(published_date__lte=timezone.now()).order_by(
#         "published_date"
#     )
#     start_date = end_date = None
#     if request.method == "POST":
#         form = PostFilterForm(request.POST)
#         if form.is_valid():
#             # get data from the form
#             title = form.cleaned_data["title"]
#             author = form.cleaned_data["author"]
#             category = form.cleaned_data["category"]
#             start_date = form.cleaned_data["start_date"]
#             end_date = form.cleaned_data["end_date"]

#             filter = Q()

#             if title:
#                 posts = posts.filter(title__icontains=title)

#             if author:
#                 posts = posts.filter(author__username=author)

#             if category:
#                 posts = posts.filter(category__in=category)

#             if start_date and end_date:
#                 start_date = form.cleaned_data["start_date"]
#                 end_date = form.cleaned_data["end_date"]
#                 posts = posts.filter(published_date__range=(start_date, end_date))
#     else:
#         form = PostFilterForm()

#     return render(request, "blog/post_list.html", {"form": form, "posts": posts})


# @require_POST
# def post_comment(request, post_id):
#     post = get_object_or_404(Post, id=post_id)

#     comment = None
#     form = CommentForm(data=request.POST)

#     if form.is_valid():
#         # create a Comment object without saving it to the database
#         comment = form.save(commit=False)
#         # assign post to the comment
#         comment.post = post
#         comment.author = request.user
#         # save the comment to the db
#         comment.save()

#     return render(
#         request, "blog/comment.html", {"form": form, "post": post, "comment": comment}
#     )


# @login_required(login_url="/login")
# def post_edit(request, pk):
#     # get post data (object based on id)
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == "POST":
#         # put post object into form
#         form = EditPostForm(request.POST, instance=post)
#         if form.is_valid():
#             user = User.objects.get(id=request.user.id)
#             # title = form.cleaned_data['title']
#             # text = form.cleaned_data['text']
#             # category = form.cleaned_data['category']
#             form.save(author=user)
#             # post = form.save(commit=False)
#             # post.author = request.user
#             # post.published_date = timezone.now()
#             # post.save()
#             # form.save_m2m()
#             return redirect("blog:post_detail", pk=post.pk)
#     else:
#         form = EditPostForm(instance=post)

#     return render(request, "blog/post_create.html", {"form": form})

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
        <div class="content container" style="display:block; padding-top:60px;">
            {% include "blog/includes/navbar.html" %}
            <div class="row m-5">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/comment.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added </h2>
    {%else%}
        {% include "blog/includes/comment_form.html" %}
    {%endif%}
{% endblock %}

blog/templates/blog/comment_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Edit Comment</h2>
    <form action="{% url "blog:comment_edit" comment.id %}" method="POST" >
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type="submit" class="btn btn-success">Edit Comment</button>
    </form>
{% endblock %}

blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>New post</h1>
<form method="POST" class="post-form">{% csrf_token %}
    {% for field in form %}
    <div> 
        {% if field.label_tag == Category %}
            <div class=d-flex> {{field}} </div>
        {%endif%}
            
        {{field.label_tag}} {{field}}
         
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li> {{error}} </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% endfor %}
    <button type="submit" class="save btn btn-success">Save</button>
</form>
<div>
    <h4><a href="/">Back</a></h4>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="post">
    <h1>{{ post.title }}</h1>
    {% if post.published_date %}
    <div class="date">
        {{ post.published_date }}
    </div>
    {% endif %}
    <b>category:</b>
    {% for cat in post.category.all %}
    <a class="btn btn-light btn-sm" href="{% url 'blog:post_category' category_id=cat.id%}" role="button">{{cat}}</a>
    {% endfor %}
    <p>{{ post.text | linebreaksbr }}</p>
    {% if user.is_authenticated %}
    <a class="btn btn-warning" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span>Update</a>
    {% endif %}
</div>

<h2>Comments</h2>
{% for comment in post.comments.all %}
<div class="card w-75 mb-3" >
    <div class="card-body">
        <p class="card-text">
            {{comment.text}}
            <h6 class="card-subtitle mb-2 text-muted">{{comment.published_date}}</h6>
        </p>
                <h6 class="card-subtitle mb-2 text-muted">commented by {{comment.author}}</h6>
        
        {% if user == comment.author or perms.blog.delete_comment and perms.blog.change_comment %}
        <div class="d-flex gap-2" >
            <div>
                <a class="btn btn-warning" href="{% url 'blog:comment_edit' comment_id=comment.id %}" > 
                    Edit
                </a> 
            </div>
            <div>
                <form action="{% url 'blog:comment_delete' comment_id=comment.id %}" method="POST"> 
                    {% csrf_token %}
                    <button type="submit" 
                        class="btn btn-danger" 
                        onclick="return confirm('Are you sure want to delete this comment?');" > 
                        Delete 
                    </button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endfor %}
{% include "blog/includes/comment_form.html" %}
<div>
    <h4><a href="/">Back</a></h4>
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>New post</h1>
<form method="POST" class="post-form">{% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-success">Save</button>
</form>
<div>
    <h4><a href="/">Back</a></h4>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="d-flex gap-3"> 
        {% for category in category_count_by_post %}
        <p> {{category.name}}: </p>
        <p> {{category.post_count}} </p>
        {% endfor %}

    </div>

    {% include "blog/includes/filter_form.html" %}

    {% for post in posts %}
        <div class="post">
            <h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
            <div class="d-flex gap-3" >
                <div class="text-muted" >
                    posted by {{post.author}}
                    {% for count_data in post_count_by_author %}
                        {%if post.author.username == count_data.author__username %}
                            {{count_data.post_count}}
                        {% endif%}
                    {% endfor %}
                </div>
                <div class="date">
                    {{ post.published_date }}
                </div>
            </div>
            <p class="text-start" >
                {{ post.text|slice:"0:300"|linebreaksbr }}...
            </p>
        </div>
    {% endfor %}
{% endblock %}